import { setPluginConfig, StrapiMediaLib } from '@_sh/strapi-plugin-ckeditor';
import type { Preset } from '@_sh/strapi-plugin-ckeditor';
import type { HeadingConfig } from 'ckeditor5';
import {
  Alignment,
  Autoformat,
  BlockQuote,
  Bold,
  Code,
  CodeBlock,
  Essentials,
  FindAndReplace,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  Highlight,
  HorizontalLine,
  HtmlEmbed,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  ListProperties,
  Paragraph,
  PasteFromOffice,
  RemoveFormat,
  SpecialCharacters,
  SpecialCharactersEssentials,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TodoList,
  Underline,
  WordCount,
} from 'ckeditor5';

const heading: HeadingConfig = {
  options: [
    { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
    { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
    { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
    { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
    { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
  ],
};

// CKEditor's default languages with plaintext first, plus bash, sql and json.
const codeBlockLanguages = [
  { language: 'plaintext', label: 'Plain text' },
  { language: 'c', label: 'C' },
  { language: 'cs', label: 'C#' },
  { language: 'cpp', label: 'C++' },
  { language: 'css', label: 'CSS' },
  { language: 'diff', label: 'Diff' },
  { language: 'html', label: 'HTML' },
  { language: 'java', label: 'Java' },
  { language: 'javascript', label: 'JavaScript' },
  { language: 'php', label: 'PHP' },
  { language: 'python', label: 'Python' },
  { language: 'ruby', label: 'Ruby' },
  { language: 'typescript', label: 'TypeScript' },
  { language: 'xml', label: 'XML' },
  { language: 'bash', label: 'Bash' },
  { language: 'sql', label: 'SQL' },
  { language: 'json', label: 'JSON' },
];

const light: Preset = {
  name: 'light',
  description: 'light: Headings, bold, italic, links, lists, images and tables',
  editorConfig: {
    licenseKey: 'GPL',
    plugins: [
      Autoformat,
      Bold,
      Italic,
      Essentials,
      Heading,
      Image,
      ImageCaption,
      ImageStyle,
      ImageToolbar,
      ImageUpload,
      Indent,
      Link,
      List,
      Paragraph,
      PasteFromOffice,
      Table,
      TableToolbar,
      TableColumnResize,
      TableCaption,
      WordCount,
      StrapiMediaLib,
    ],
    toolbar: [
      'undo',
      'redo',
      '|',
      'heading',
      '|',
      'bold',
      'italic',
      '|',
      'link',
      'strapiMediaLib',
      'insertTable',
      '|',
      'bulletedList',
      'numberedList',
    ],
    heading,
    image: {
      toolbar: [
        'imageStyle:inline',
        'imageStyle:block',
        'imageStyle:side',
        '|',
        'toggleImageCaption',
        'imageTextAlternative',
      ],
    },
    table: {
      contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells', '|', 'toggleTableCaption'],
    },
  },
};

const rich: Preset = {
  name: 'rich',
  description: 'rich: Full formatting: fonts, colors, code blocks, tables, images and more',
  editorConfig: {
    licenseKey: 'GPL',
    plugins: [
      Alignment,
      Autoformat,
      Bold,
      Italic,
      Underline,
      Strikethrough,
      Code,
      Subscript,
      Superscript,
      BlockQuote,
      CodeBlock,
      Essentials,
      FontSize,
      FontFamily,
      FontColor,
      FontBackgroundColor,
      FindAndReplace,
      Heading,
      HorizontalLine,
      HtmlEmbed,
      Image,
      ImageCaption,
      ImageStyle,
      ImageToolbar,
      ImageUpload,
      ImageResize,
      Indent,
      IndentBlock,
      Link,
      LinkImage,
      List,
      ListProperties,
      TodoList,
      Paragraph,
      PasteFromOffice,
      RemoveFormat,
      SpecialCharacters,
      SpecialCharactersEssentials,
      Table,
      TableToolbar,
      TableProperties,
      TableCellProperties,
      TableColumnResize,
      TableCaption,
      WordCount,
      Highlight,
      StrapiMediaLib,
    ],
    toolbar: {
      items: [
        'undo',
        'redo',
        '|',
        'findAndReplace',
        'selectAll',
        '|',
        'heading',
        '|',
        'fontSize',
        'fontFamily',
        'fontColor',
        'fontBackgroundColor',
        '|',
        'bold',
        'italic',
        'underline',
        'strikethrough',
        'superscript',
        'subscript',
        'code',
        'removeFormat',
        '-',
        'link',
        'strapiMediaLib',
        'insertTable',
        'horizontalLine',
        'blockQuote',
        'codeBlock',
        'htmlEmbed',
        'specialCharacters',
        'highlight',
        '|',
        'alignment',
        '|',
        'bulletedList',
        'numberedList',
        'todoList',
        'outdent',
        'indent',
      ],
      shouldNotGroupWhenFull: true,
    },
    heading,
    codeBlock: { languages: codeBlockLanguages },
    list: { properties: { styles: true, startIndex: true, reversed: true } },
    image: {
      resizeUnit: '%',
      resizeOptions: [
        { name: 'resizeImage:original', value: null, icon: 'original' },
        { name: 'resizeImage:25', value: '25', icon: 'small' },
        { name: 'resizeImage:50', value: '50', icon: 'medium' },
        { name: 'resizeImage:75', value: '75', icon: 'large' },
      ],
      toolbar: [
        'imageStyle:inline',
        'imageStyle:block',
        'imageStyle:side',
        '|',
        'toggleImageCaption',
        'imageTextAlternative',
        '|',
        'linkImage',
        '|',
        'resizeImage:25',
        'resizeImage:50',
        'resizeImage:75',
        'resizeImage:original',
      ],
    },
    table: {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        '|',
        'tableCellProperties',
        'tableProperties',
        '|',
        'toggleTableCaption',
      ],
    },
    fontSize: {
      options: [9, 11, 13, 'default', 17, 19, 21, 27, 35],
      supportAllValues: false,
    },
    fontFamily: {
      options: [
        'default',
        'Arial, Helvetica Neue, Helvetica, Source Sans Pro, sans-serif',
        'Courier New, Courier, monospace',
        'Georgia, serif',
        'Lucida Sans Unicode, Lucida Grande, sans-serif',
        'Tahoma, Geneva, sans-serif',
        'Times New Roman, Times, serif',
        'Trebuchet MS, Helvetica, sans-serif',
        'Verdana, Geneva, sans-serif',
        'Roboto, Roboto Black, Roboto Medium, Roboto Light, sans-serif',
      ],
      supportAllValues: true,
    },
    fontColor: { columns: 5, documentColors: 10 },
    fontBackgroundColor: { columns: 5, documentColors: 10 },
  },
};

export default {
  register() {
    setPluginConfig({ presets: [light, rich] });
  },
};
